include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    constant_identifier_names: ignore
    invalid_annotation_target: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
linter:
  rules:
    - avoid_redundant_argument_values
    - exhaustive_cases
    - sort_constructors_first
    - prefer_single_quotes
    - prefer_relative_imports
    - require_trailing_commas
    - sort_pub_dependencies
