name: backdoor_flutter
version: 0.1.4
homepage: https://github.com/gktirkha/backdoor_flutter/
repository: https://github.com/gktirkha/backdoor_flutter/
description: The BackdoorFlutter library offers a comprehensive solution for managing payment statuses in Flutter applications. It provides functionalities to initialize app configurations, check payment status, and handle various scenarios like trial periods and limited launches. With customizable callbacks for different states (e.g., paid, unpaid, trial), robust error handling, and built-in logging, this library streamlines payment management while ensuring a smooth user experience. Ideal for developers seeking to integrate subscription and payment validation seamlessly into their apps.

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
