name: backdoor_flutter
version: 0.1.4
homepage: https://github.com/gktirkha/backdoor_flutter/
repository: https://github.com/gktirkha/backdoor_flutter/
description: BackdoorFlutter simplifies payment management in Flutter apps, providing status checks, trial handling, and customizable callbacks for an improved user experience.

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
