name: backdoor_flutter
description: A new Flutter package project.
version: 0.0.1
homepage: null
main: lib/backdoor_flutter.dart

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
